name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-ziglib:
    name: Test ziglib
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
            version: 0.11.0

      - name: Run test script
        run: ./ziglib/test.sh

  test-pylib:
    name: Test pylib
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pylib/requirements.txt

      - name: Run test script
        run: ./pylib/test.sh

  test-csl:
    name: Test csl
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm2cpio
          sudo apt-get install -y golang-go
          mkdir -p ~/apptainer
          # echo 'export PATH="$HOME/apptainer/bin:$PATH"' >> ~/.bashrc
          echo "$HOME/apptainer/bin" >> $GITHUB_PATH
          curl -s https://raw.githubusercontent.com/apptainer/apptainer/d77d6f1eb099855f284a482992140d5eeb18be8a/tools/install-unprivileged.sh | bash -s - ~/apptainer

      - name: Test Apptainer
        run: |
          apptainer --version
