name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-ziglib:
    name: Test ziglib
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
            version: 0.11.0

      - name: Run test script
        run: ./ziglib/test.sh

  test-pylib:
    name: Test pylib
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pylib/requirements.txt

      - name: Run test script
        run: ./pylib/test.sh
